sudo: required
services:
    - docker

before_install:
    - docker build -t vedhaaa/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vedhaaa/docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-560749283904"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
