sudo: required
services:
    - docker

before_install:
    - docker build -t vedhaaa/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vedhaaa/docker-react npm run test -- --coverage

